# basic settings
title: The Biggert Collection
description: The Biggert Collection of Architectural Vignettes on Commercial Stationery
baseurl: '/biggert_static'
url: ''

# build settings
markdown: kramdown
theme: minima
exclude: [Gemfile*, vendor, Rakefile, README.md]
permalink: pretty

# wax collection settings
collections:
  biggert:
    source: biggert-items.json
    layout: iiif-image-page
    output: true
